name: Backend CI

on:
  push:
    branches: [ development, main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
  pull_request:
    branches: [ development, main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
  workflow_dispatch:

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  BRANCH: ${{ github.ref_name }}
  IMAGE_BASE: ${{ secrets.ACR_LOGIN_SERVER }}/my-backend
  IMAGE_SHA:  ${{ env.IMAGE_BASE }}:${{ github.sha }}
  IMAGE_BR:   ${{ env.IMAGE_BASE }}:${{ env.BRANCH }}

jobs:
  test:
    name: Smoke/Test (PR only)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - run: docker build -f backend/Dockerfile backend

  build-push:
    name: Build & Push (branch pushes)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name "${{ env.ACR_NAME }}"

      - uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_SHA }}
            ${{ env.IMAGE_BR }}

      - name: Logout Azure
        if: always()
        run: az logout

