name: Frontend CI

on:
  push:
    branches: [ development, main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    branches: [ development, main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  workflow_dispatch:

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  BRANCH: ${{ github.ref_name }}                  # development or main
  IMAGE_BASE: ${{ secrets.ACR_LOGIN_SERVER }}/my-frontend
  IMAGE_SHA:  ${{ env.IMAGE_BASE }}:${{ github.sha }}
  IMAGE_BR:   ${{ env.IMAGE_BASE }}:${{ env.BRANCH }}

jobs:
  test:
    name: Test (PR only)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    defaults: { run: { working-directory: frontend } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm', cache-dependency-path: 'frontend/package-lock.json' }
      - run: npm ci
      - run: npm test --if-present
      - run: npm run build --if-present

  build-push:
    name: Build & Push (branch pushes)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name "${{ env.ACR_NAME }}"

      - uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_SHA }}
            ${{ env.IMAGE_BR }}

      - name: Logout Azure
        if: always()
        run: az logout
