name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches: [ development, main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    branches: [ development, main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Optional PR check: build only (no push)
  pr-check:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build (no push)
        run: docker build -t test-frontend ./frontend

  build-and-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # for azure/login OIDC
      contents: read
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      BRANCH: ${{ github.ref_name }}
      SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name "${{ env.ACR_NAME }}"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image (keep your repo path)
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker tag  ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.BRANCH }}
          docker tag  ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.SHA }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.BRANCH }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.SHA }}

      - name: Azure logout
        if: always()
        run: az logout
